export const StorageKeys = {
  PARAM_VALUES_KEY: "linkParamValues",
  INJECT_ON_LOAD_KEY: "injectOnLoad",
  LINKS_OVERLAY_KEY: "linksJsonOverlay",
  INJECT_ON_LOAD_ENABLED_KEY: "injectOnLoadEnabled",
  LAST_ORIGINS_KEY: "lastOrigins",
  SECTION_TAB_KEY: "activeSectionTab",
  ADD_SCRIPT_EXPANDED_KEY: "addScriptExpanded",
  LINK_BUILDER_PREFILL_KEY: "linkBuilderPrefill",
  PARAM_PROMPT_KEY: "linkParamPrompt",
  LINK_BUILDER_SECTION_KEY: "linkBuilderSection",
  CATALOG_ORDER_KEY: "catalogOrder",
  LINK_SHORTCUT_SLOTS_KEY: "linkShortcutSlots",
  LAST_ACTIVATED_LINK_KEY: "lastActivatedLinkKey",
  PREFERRED_OPEN_DEFAULT_KEY: "preferredOpenDefault",
};
